import { z } from "zod";

export const weatherSchema = z.object({
  latitude: z.number(),
  longitude: z.number(),
  generationtime_ms: z.number(),
  utc_offset_seconds: z.number(),
  timezone: z.string(),
  timezone_abbreviation: z.string(),
  elevation: z.number(),
  current_units: z.object({
    time: z.string(),
    interval: z.string(),
    temperature_2m: z.string(),
    precipitation: z.string(),
    relative_humidity_2m: z.string(),
    apparent_temperature: z.string(),
    weather_code: z.string(),
    wind_speed_10m: z.string(),
    is_day: z.string(),
  }),
  current: z.object({
    time: z.string(),
    interval: z.number(),
    temperature_2m: z.number(),
    precipitation: z.number(),
    relative_humidity_2m: z.number(),
    apparent_temperature: z.number(),
    weather_code: z.number(),
    wind_speed_10m: z.number(),
    is_day: z.number(),
  }),
  hourly_units: z.object({
    time: z.string(),
    temperature_2m: z.string(),
    apparent_temperature: z.string(),
    wind_speed_10m: z.string(),
    relative_humidity_2m: z.string(),
    precipitation: z.string(),
    weather_code: z.string(),
    is_day: z.string(),
  }),
  hourly: z.object({
    time: z.array(z.string()),
    temperature_2m: z.array(z.number()),
    apparent_temperature: z.array(z.number()),
    wind_speed_10m: z.array(z.number()),
    relative_humidity_2m: z.array(z.number()),
    precipitation: z.array(z.number()),
    weather_code: z.array(z.number()),
    is_day: z.array(z.number()),
  }),
  daily_units: z.object({
    time: z.string(),
    temperature_2m_max: z.string(),
    temperature_2m_min: z.string(),
    weather_code: z.string(),
  }),
  daily: z.object({
    time: z.array(z.string()),
    temperature_2m_max: z.array(z.number()),
    temperature_2m_min: z.array(z.number()),
    weather_code: z.array(z.number()),
  }),
});
